services:
  proxy_server:
    image: paxton0222/proxy_server
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - paxton0222/proxy_server
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./proxy.txt:/app/proxy.txt